env:
  browser: false
  commonjs: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    modules: true
plugins:
  - '@typescript-eslint'
rules:
    "@typescript-eslint/adjacent-overload-signatures": "error"
    "@typescript-eslint/ban-ts-ignore": "error"
    "@typescript-eslint/ban-types": "error"
    "camelcase": "off"
    "@typescript-eslint/camelcase": "error"
    "@typescript-eslint/class-name-casing": "error"
    "@typescript-eslint/consistent-type-assertions": "error"
    "@typescript-eslint/explicit-function-return-type": "warn"
    "@typescript-eslint/interface-name-prefix": "error"
    "@typescript-eslint/member-delimiter-style": "error"
    "no-array-constructor": "off"
    "@typescript-eslint/no-array-constructor": "error"
    "no-empty-function": "off"
    "@typescript-eslint/no-empty-function": "error"
    "@typescript-eslint/no-empty-interface": "error"
    "@typescript-eslint/no-explicit-any": "warn"
    "@typescript-eslint/no-inferrable-types": "error"
    "@typescript-eslint/no-misused-new": "error"
    "@typescript-eslint/no-namespace": "error"
    "@typescript-eslint/no-non-null-assertion": "warn"
    "@typescript-eslint/no-this-alias": "error"
    "no-unused-vars": "off"
    "@typescript-eslint/no-unused-vars": "warn"
    "no-use-before-define": "off"
    "@typescript-eslint/no-use-before-define": "error"
    "@typescript-eslint/no-var-requires": "error"
    "@typescript-eslint/prefer-namespace-keyword": "error"
    "@typescript-eslint/triple-slash-reference": "error"
    "@typescript-eslint/type-annotation-spacing": "error"
    "no-var": "error"
    "prefer-const": "error"
    "prefer-rest-params": "error"
    "prefer-spread": "error"